export const SCHEDULER_ENV_KEYS = {
  ENABLED: 'SCHEDULER_ENABLED',
  TIMEZONE: 'SCHEDULER_TIMEZONE',

  MEDIA_CLEANUP_ENABLED: 'SCHEDULER_MEDIA_CLEANUP_ENABLED',
  MEDIA_CLEANUP_CRON: 'SCHEDULER_MEDIA_CLEANUP_CRON',
  MEDIA_CLEANUP_OLDER_THAN_MINUTES:
    'SCHEDULER_MEDIA_CLEANUP_OLDER_THAN_MINUTES',
  MEDIA_CLEANUP_DRY_RUN: 'SCHEDULER_MEDIA_CLEANUP_DRY_RUN',

  QUEUE_HEALTH_ENABLED: 'SCHEDULER_QUEUE_HEALTH_ENABLED',
  QUEUE_HEALTH_CRON: 'SCHEDULER_QUEUE_HEALTH_CRON',
  QUEUE_HEALTH_FAILED_WARNING_THRESHOLD:
    'SCHEDULER_QUEUE_HEALTH_FAILED_WARNING_THRESHOLD',
} as const;

export const SCHEDULER_DEFAULTS = {
  ENABLED: true,
  TIMEZONE: 'Asia/Tehran',

  MEDIA_CLEANUP_ENABLED: true,
  MEDIA_CLEANUP_CRON: '0 */6 * * *',
  MEDIA_CLEANUP_OLDER_THAN_MINUTES: 1_440,
  MEDIA_CLEANUP_DRY_RUN: false,

  QUEUE_HEALTH_ENABLED: true,
  QUEUE_HEALTH_CRON: '*/5 * * * *',
  QUEUE_HEALTH_FAILED_WARNING_THRESHOLD: 10,
} as const;

export const SCHEDULER_TASK_NAMES = {
  MEDIA_CLEANUP: 'scheduler.media-cleanup',
  QUEUE_HEALTH: 'scheduler.queue-health',
} as const;

export const SCHEDULER_LOCK_KEYS = {
  MEDIA_CLEANUP: 'vexo:scheduler:media-cleanup',
  QUEUE_HEALTH: 'vexo:scheduler:queue-health',
} as const;

export type SchedulerEnvKey =
  (typeof SCHEDULER_ENV_KEYS)[keyof typeof SCHEDULER_ENV_KEYS];

export type SchedulerTaskName =
  (typeof SCHEDULER_TASK_NAMES)[keyof typeof SCHEDULER_TASK_NAMES];

export type SchedulerLockKey =
  (typeof SCHEDULER_LOCK_KEYS)[keyof typeof SCHEDULER_LOCK_KEYS];
