export const QUEUE_NAMES = {
  NOTIFICATION: 'notification',
  EMAIL: 'email',
  SMS: 'sms',
  INVOICE: 'invoice',
  ORDER: 'order',
  AI: 'ai',
  MEDIA: 'media',
  ANALYTICS: 'analytics',
  DEAD_LETTER: 'dead-letter',
} as const;

export const QUEUE_JOB_NAMES = {
  NOTIFICATION_DATABASE: 'notification.database',
  NOTIFICATION_PUSH: 'notification.push',
  NOTIFICATION_DELIVERY: 'notification.delivery',

  EMAIL_SEND: 'email.send',

  SMS_SEND: 'sms.send',

  INVOICE_GENERATE: 'invoice.generate',

  ORDER_POST_CREATED: 'order.post-created',
  ORDER_POST_PAID: 'order.post-paid',

  AI_PROCESS: 'ai.process',
  AI_PRODUCT_CONTENT_GENERATE: 'ai.product-content.generate',
  AI_MARKETING_CONTENT_GENERATE: 'ai.marketing-content.generate',
  AI_SEMANTIC_INDEX_PRODUCT: 'ai.semantic-index.product',
  AI_SEARCH_CONTEXT_BUILD: 'ai.search-context.build',
  AI_SALES_ADVICE_GENERATE: 'ai.sales-advice.generate',

  MEDIA_CLEANUP_TEMPORARY: 'media.cleanup-temporary',
  MEDIA_OPTIMIZE_IMAGE: 'media.optimize-image',
  MEDIA_GENERATE_THUMBNAIL: 'media.generate-thumbnail',

  ANALYTICS_CAPTURE_EVENT: 'analytics.capture-event',

  DEAD_LETTER_CAPTURE: 'dead-letter.capture',
} as const;

export const QUEUE_DEFAULTS = {
  KEY_PREFIX: 'vexo:queue',
  DEFAULT_ATTEMPTS: 3,
  DEFAULT_BACKOFF_DELAY_MS: 5_000,
  DEFAULT_TIMEOUT_MS: 60_000,
  REMOVE_ON_COMPLETE_COUNT: 1_000,
  REMOVE_ON_FAIL_COUNT: 5_000,
  WORKER_CONCURRENCY: 5,
  STALLED_INTERVAL_MS: 30_000,
  MAX_STALLED_COUNT: 1,
} as const;

export const QUEUE_OPERATIONAL_HEALTH_DEFAULTS = {
  BACKLOG_WARNING_THRESHOLD: 25,
  BACKLOG_CRITICAL_THRESHOLD: 100,
  FAILED_WARNING_THRESHOLD: 10,
  FAILED_CRITICAL_THRESHOLD: 50,
  DELAYED_WARNING_THRESHOLD: 25,
  DELAYED_CRITICAL_THRESHOLD: 100,
  FAILURE_RATE_WARNING_PERCENT: 20,
  FAILURE_RATE_CRITICAL_PERCENT: 50,
  FAILURE_RATE_MIN_SAMPLE: 20,
} as const;

export const QUEUE_OPERATIONAL_HEALTH_ENV_KEYS = {
  BACKLOG_WARNING_THRESHOLD: 'QUEUE_HEALTH_BACKLOG_WARNING_THRESHOLD',
  BACKLOG_CRITICAL_THRESHOLD: 'QUEUE_HEALTH_BACKLOG_CRITICAL_THRESHOLD',
  FAILED_WARNING_THRESHOLD: 'QUEUE_HEALTH_FAILED_WARNING_THRESHOLD',
  FAILED_CRITICAL_THRESHOLD: 'QUEUE_HEALTH_FAILED_CRITICAL_THRESHOLD',
  DELAYED_WARNING_THRESHOLD: 'QUEUE_HEALTH_DELAYED_WARNING_THRESHOLD',
  DELAYED_CRITICAL_THRESHOLD: 'QUEUE_HEALTH_DELAYED_CRITICAL_THRESHOLD',
  FAILURE_RATE_WARNING_PERCENT: 'QUEUE_HEALTH_FAILURE_RATE_WARNING_PERCENT',
  FAILURE_RATE_CRITICAL_PERCENT: 'QUEUE_HEALTH_FAILURE_RATE_CRITICAL_PERCENT',
  FAILURE_RATE_MIN_SAMPLE: 'QUEUE_HEALTH_FAILURE_RATE_MIN_SAMPLE',
} as const;

export const QUEUE_ENV_KEYS = {
  ENABLED: 'QUEUE_ENABLED',
  REDIS_REQUIRED: 'QUEUE_REDIS_REQUIRED',
  PREFIX: 'QUEUE_PREFIX',
  DEFAULT_ATTEMPTS: 'QUEUE_DEFAULT_ATTEMPTS',
  DEFAULT_BACKOFF_DELAY_MS: 'QUEUE_DEFAULT_BACKOFF_DELAY_MS',
  DEFAULT_TIMEOUT_MS: 'QUEUE_DEFAULT_TIMEOUT_MS',
  REMOVE_ON_COMPLETE_COUNT: 'QUEUE_REMOVE_ON_COMPLETE_COUNT',
  REMOVE_ON_FAIL_COUNT: 'QUEUE_REMOVE_ON_FAIL_COUNT',
  WORKER_CONCURRENCY: 'QUEUE_WORKER_CONCURRENCY',
  STALLED_INTERVAL_MS: 'QUEUE_STALLED_INTERVAL_MS',
  MAX_STALLED_COUNT: 'QUEUE_MAX_STALLED_COUNT',
} as const;

export const QUEUE_REDIS_ENV_KEYS = {
  URL: 'QUEUE_REDIS_URL',
  HOST: 'QUEUE_REDIS_HOST',
  PORT: 'QUEUE_REDIS_PORT',
  DB: 'QUEUE_REDIS_DB',
  PASSWORD: 'QUEUE_REDIS_PASSWORD',
  TLS: 'QUEUE_REDIS_TLS',
  CONNECT_TIMEOUT_MS: 'QUEUE_REDIS_CONNECT_TIMEOUT_MS',
  MAX_RETRIES: 'QUEUE_REDIS_MAX_RETRIES',
} as const;

export const ALL_QUEUE_NAMES = [
  QUEUE_NAMES.NOTIFICATION,
  QUEUE_NAMES.EMAIL,
  QUEUE_NAMES.SMS,
  QUEUE_NAMES.INVOICE,
  QUEUE_NAMES.ORDER,
  QUEUE_NAMES.AI,
  QUEUE_NAMES.MEDIA,
  QUEUE_NAMES.ANALYTICS,
  QUEUE_NAMES.DEAD_LETTER,
] as const;

export type QueueName = (typeof ALL_QUEUE_NAMES)[number];
export type QueueJobName =
  (typeof QUEUE_JOB_NAMES)[keyof typeof QUEUE_JOB_NAMES];
